sonar.projectKey=ayudyah29_node-ci-sonar
sonar.organization=ayudyah-org
sonar.projectName=node-ci-sonar
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=test/**/*.test.js
sonar.javascript.lcov.reportPaths=coverage/lcov.info
